samples:
  CHM13:
    fasta: T2T-CHM13v2.fasta
    regions: target_region.bed
    bam: T2T-CHM13v2.bam

# Species to use for RepeatMasker
# See https://www.repeatmasker.org/genomicDatasets/RMGenomicDatasets.html
species: "human"

# Use container image globally
container: "docker://logsdonlab/cdr-finder:latest"

# Restrict to alpha-satellite repeat annotated sequence.
# NOTE: If disabled, this will give false positives if the region is not well curated.
restrict_alr: true

# Size of the methylation windows to average over
window_size: 5000

# Size of ALR repeat stretches to include in search of CDR
alr_threshold: 100000

# Distance to merge adjacent CDRs. Can omit.
bp_merge: 1

# Threshold percent of the average methylation percentage needed as the minimal height of a valley from the median.
# ex. 0.1 allows valleys with a height from the median equal to 10% of the median.
height_perc_valley_threshold: 0.2

prom_perc_valley_threshold: 0.1

# Baseline average methylation per centromere.
# Adjusts height_perc_valley_threshold and prom_perc_valley_threshold based on avg methyl coverage relative to baseline.
# Will only increase thresholds and never reduce them.
# Reduces false positives in centromeres with low methylation relative to coverage.
# ex.
#   avg methyl coverage is 0.2
#   methyl_avg_baseline is 0.4
#   0.4 / 0.2 = 2
#   thresholds will be multiplied by 2
# Can be omitted.
baseline_avg_methyl: 0.4

bp_alr_merge: 8000

bp_edge: 500000

extend_edges_std: -1

# Add red horizontal bar where CDR is.
add_hbar: true

# Opacity of red overlap region
overlap_opacity: 0.34
