name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    # https://github.com/orgs/community/discussions/25678#discussioncomment-5242449
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: Checkout directory.
      uses: actions/checkout@v3
      with:
        lfs: 'true'

    - name: Setup Miniforge.
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: smk

    - name: Get date.
      id: get-date
      run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache conda env.
      uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key:
          conda-${{ runner.os }}--${{ runner.arch }}--${{
          steps.get-date.outputs.today }}-${{
          hashFiles('test/env_dev.yaml') }}-${{ env.CACHE_NUMBER }}
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      id: cache

    - name: Update environment.
      run:
        conda env update -n smk -f env.yaml
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Test can generate Dockerfile.
      run: |
        make dockerfile

    - name: Test scripts.
      run: |
        pytest -vvv

    - name: Test run chr8 and chr21 workflow.
      run: |
        snakemake -c 2 -p \
        --sdm apptainer conda \
        --configfile test/config/config.yaml \
        --show-failed-logs \
        --apptainer-args "--bind $HOME:$HOME"
